"""Agent observability: full-trace capture, persistence, and replay.

Autonomous agents are only trustworthy if you can see what they did. This
module gives the forecasting notebooks a single, auditable record of every
run: the question, every prompt an agent received, every raw model response,
every search query and the documents it returned, and the structured forecast
that came out the other end.

Three pieces, each independent:

1. ``TracingLLMClient`` wraps *any* ``LLMClient`` and records every call —
   the exact messages sent in and the raw text returned — without changing a
   line of agent logic. Because every agent in the chapter (research, debate,
   supervisor) talks to the model through the same ``complete_with_usage``
   interface, wrapping the client captures the whole conversation for free.

2. ``RunTrace`` bundles the question, the structured artifacts, and the raw
   model I/O into one object that serializes to JSON (``save``) and reloads
   (``load``). That file is the durable, replayable record of a point-in-time
   run — the thing you hand to a reviewer who asks "show me exactly what the
   agents saw and said."

3. The ``show_*`` renderers turn an in-memory artifact (or a reloaded trace)
   into a clean, untruncated, chronological readout so a reader can follow how
   each agent proceeds over time.

The captured JSON lives in ``forecast_traces/`` (git-ignored, regenerated by
re-running a notebook), mirroring the ``operator_artifacts/`` convention.
"""

from __future__ import annotations

import dataclasses
import itertools
import json
import textwrap
import threading
from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import Enum
from pathlib import Path
from typing import Any
from uuid import uuid4

from agent_providers import ChatMessage, LLMClient
from agent_schemas import (
    AgentForecastArtifact,
    AgentTrace,
    AggregationResult,
    DebateArtifact,
    DebateRound,
    EvidenceQuality,
    ForecastQuestion,
    ForecastResult,
    SearchResult,
    Sentiment,
    SupervisorArtifact,
    TokenUsage,
)

TRACES_DIR = Path(__file__).resolve().parent / "forecast_traces"

# A process-wide monotonic counter so calls captured by *different* tracers
# (e.g. one per agent thread in NB06) can still be merged back into the true
# chronological order. ``itertools.count`` is not atomic across threads, so we
# guard it with a lock.
_SEQ = itertools.count()
_SEQ_LOCK = threading.Lock()


def _next_seq() -> int:
    with _SEQ_LOCK:
        return next(_SEQ)


def _now_iso() -> str:
    return datetime.now(UTC).isoformat(timespec="seconds")


# ---------------------------------------------------------------------------
# Serialization helper
# ---------------------------------------------------------------------------


def to_serializable(obj: Any) -> Any:
    """Recursively convert dataclasses, enums, and containers to JSON-safe types."""
    if dataclasses.is_dataclass(obj) and not isinstance(obj, type):
        return to_serializable(dataclasses.asdict(obj))
    if isinstance(obj, Enum):
        return obj.value
    if isinstance(obj, dict):
        return {str(k): to_serializable(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [to_serializable(v) for v in obj]
    return obj


# ---------------------------------------------------------------------------
# LLM call capture
# ---------------------------------------------------------------------------


@dataclass(slots=True)
class LLMCall:
    """One model invocation: everything sent in, everything returned."""

    seq: int
    label: str
    model: str
    json_mode: bool
    messages: list[dict[str, str]]  # the full prompt: [{"role", "content"}, ...]
    response: str  # raw model output, untruncated
    input_tokens: int
    output_tokens: int
    total_tokens: int
    timestamp: str


class TracingLLMClient:
    """Wraps any ``LLMClient`` and records every call.

    Drop-in replacement for the wrapped client — it satisfies the same
    ``LLMClient`` protocol (``model_name``, ``complete``,
    ``complete_with_usage``) and forwards to the inner client, appending an
    ``LLMCall`` record on every completion.

    Thread-safe: ``list.append`` is atomic under CPython's GIL and the
    sequence counter is locked, so a single tracer can be shared across
    threads. In practice (e.g. NB06's ``ThreadPoolExecutor``) it is cleaner to
    give each agent its own tracer with a distinct ``label`` and
    :func:`merge_calls` them afterwards, so each call is attributed to the
    agent that made it.
    """

    def __init__(self, inner: LLMClient, label: str = "") -> None:
        self._inner = inner
        self.label = label
        self.calls: list[LLMCall] = []

    @property
    def model_name(self) -> str:
        return self._inner.model_name

    def complete(self, messages: list[ChatMessage], json_mode: bool = False) -> str:
        text, _ = self.complete_with_usage(messages, json_mode)
        return text

    def complete_with_usage(self, messages: list[ChatMessage], json_mode: bool = False):
        text, usage = self._inner.complete_with_usage(messages, json_mode)
        self.calls.append(
            LLMCall(
                seq=_next_seq(),
                label=self.label,
                model=self._inner.model_name,
                json_mode=json_mode,
                messages=[{"role": m.role, "content": m.content} for m in messages],
                response=text,
                input_tokens=usage.input_tokens,
                output_tokens=usage.output_tokens,
                total_tokens=usage.total_tokens,
                timestamp=_now_iso(),
            )
        )
        return text, usage


def trace_llm(inner: LLMClient, label: str = "") -> TracingLLMClient:
    """Convenience constructor: ``llm = trace_llm(create_llm_client(...))``."""
    return TracingLLMClient(inner, label=label)


def merge_calls(*sources: TracingLLMClient | list[LLMCall]) -> list[LLMCall]:
    """Combine call logs from several tracers into one chronological list."""
    calls: list[LLMCall] = []
    for src in sources:
        calls.extend(src.calls if isinstance(src, TracingLLMClient) else src)
    return sorted(calls, key=lambda c: c.seq)


# ---------------------------------------------------------------------------
# Run trace: the durable, replayable record
# ---------------------------------------------------------------------------


@dataclass
class RunTrace:
    """A complete, serializable record of one forecasting run.

    Holds the structured artifacts (what came out) alongside the raw model I/O
    (what went in and came back), so the run can be inspected, replayed, and
    analyzed long after the live providers have moved on.
    """

    notebook: str
    provider: str
    question: dict[str, Any] | None = None
    params: dict[str, Any] = field(default_factory=dict)

    # Structured artifacts (any subset may be present)
    agents: list[dict[str, Any]] = field(default_factory=list)
    aggregation: dict[str, Any] | None = None
    debate: dict[str, Any] | None = None
    supervisor: dict[str, Any] | None = None
    final_probability: float | None = None
    final_confidence: float | None = None

    # Raw model conversation, chronological
    llm_calls: list[dict[str, Any]] = field(default_factory=list)

    notes: str = ""
    created_at: str = field(default_factory=_now_iso)
    run_id: str = field(default_factory=lambda: uuid4().hex[:12])

    @classmethod
    def capture(
        cls,
        *,
        notebook: str,
        provider: str,
        question: ForecastQuestion | None = None,
        params: dict[str, Any] | None = None,
        agents: list[AgentForecastArtifact] | None = None,
        aggregation: Any = None,
        debate: DebateArtifact | None = None,
        supervisor: SupervisorArtifact | None = None,
        final_probability: float | None = None,
        final_confidence: float | None = None,
        llm_calls: list[LLMCall] | None = None,
        notes: str = "",
    ) -> RunTrace:
        """Build a RunTrace from in-memory artifacts and a captured call log."""
        return cls(
            notebook=notebook,
            provider=provider,
            question=to_serializable(question) if question is not None else None,
            params=params or {},
            agents=[to_serializable(a) for a in (agents or [])],
            aggregation=to_serializable(aggregation) if aggregation is not None else None,
            debate=to_serializable(debate) if debate is not None else None,
            supervisor=to_serializable(supervisor) if supervisor is not None else None,
            final_probability=final_probability,
            final_confidence=final_confidence,
            llm_calls=[to_serializable(c) for c in (llm_calls or [])],
            notes=notes,
        )

    @classmethod
    def from_result(
        cls,
        result: ForecastResult,
        *,
        notebook: str,
        provider: str,
        params: dict[str, Any] | None = None,
        llm_calls: list[LLMCall] | None = None,
        notes: str = "",
    ) -> RunTrace:
        """Build a RunTrace from a full pipeline ``ForecastResult`` (NB08)."""
        return cls.capture(
            notebook=notebook,
            provider=provider,
            question=result.question,
            params=params,
            agents=result.agents,
            aggregation=result.aggregation,
            debate=result.debate,
            supervisor=result.supervisor,
            final_probability=result.final_probability,
            final_confidence=result.final_confidence,
            llm_calls=llm_calls,
            notes=notes,
        )

    def to_json(self) -> str:
        return json.dumps(to_serializable(self), indent=2, default=str)

    def save(self, directory: Path | str = TRACES_DIR) -> Path:
        """Write the trace to ``<notebook>_<timestamp>_<run_id>.json``."""
        directory = Path(directory)
        directory.mkdir(parents=True, exist_ok=True)
        stamp = self.created_at.replace(":", "").replace("-", "").replace("+0000", "Z")
        path = directory / f"{self.notebook}_{stamp}_{self.run_id}.json"
        path.write_text(self.to_json(), encoding="utf-8")
        return path

    @classmethod
    def load(cls, path: Path | str) -> RunTrace:
        """Reload a trace from disk for replay/analysis."""
        data = json.loads(Path(path).read_text(encoding="utf-8"))
        known = {f.name for f in dataclasses.fields(cls)}
        return cls(**{k: v for k, v in data.items() if k in known})

    def call_log(self) -> list[LLMCall]:
        """Reconstruct ``LLMCall`` objects from the stored dicts (for replay)."""
        return [LLMCall(**c) for c in self.llm_calls]

    def total_tokens(self) -> int:
        return sum(c.get("total_tokens", 0) for c in self.llm_calls)

    # -- Rehydration: stored dicts → typed artifacts -----------------------
    # ``load`` returns ``agents``/``aggregation``/``debate``/``supervisor`` as
    # plain dicts (JSON has no dataclasses). The notebook display cells expect
    # the same typed objects a live run produces, so these methods rebuild them.
    # That is what makes replay a drop-in substitute for a live run: the cells
    # downstream cannot tell whether the artifacts came from the model or disk.

    def question_obj(self) -> ForecastQuestion | None:
        """Rebuild the ``ForecastQuestion`` from the stored dict."""
        return _rehydrate_question(self.question)

    def agent_artifacts(self) -> list[AgentForecastArtifact]:
        """Rebuild the list of ``AgentForecastArtifact`` from stored dicts."""
        return [_rehydrate_agent(a) for a in self.agents]

    def aggregation_obj(self) -> AggregationResult | None:
        """Rebuild the ``AggregationResult`` from the stored dict."""
        return AggregationResult(**self.aggregation) if self.aggregation else None

    def debate_obj(self) -> DebateArtifact | None:
        """Rebuild the ``DebateArtifact`` from the stored dict."""
        return _rehydrate_debate(self.debate)

    def supervisor_obj(self) -> SupervisorArtifact | None:
        """Rebuild the ``SupervisorArtifact`` from the stored dict."""
        return _rehydrate_supervisor(self.supervisor)

    def forecast_result(self) -> ForecastResult:
        """Rebuild a full ``ForecastResult`` (NB08 pipeline) from the trace.

        ``duration_seconds`` is not part of the persisted record (wall-clock is
        not reproducible), so it comes back ``None``; the token total is
        reconstructed from the saved per-stage usage.
        """
        agents = self.agent_artifacts()
        debate = self.debate_obj()
        supervisor = self.supervisor_obj()
        total = TokenUsage()
        for a in agents:
            total = total + a.token_usage
        if debate is not None:
            total = total + debate.token_usage
        if supervisor is not None:
            total = total + supervisor.token_usage
        question = self.question_obj()
        return ForecastResult(
            question=question if question is not None else ForecastQuestion(question=""),
            agents=agents,
            aggregation=self.aggregation_obj(),
            debate=debate,
            supervisor=supervisor,
            final_probability=self.final_probability if self.final_probability is not None else 0.5,
            final_confidence=self.final_confidence if self.final_confidence is not None else 0.5,
            total_token_usage=total,
            duration_seconds=None,
        )


# ---------------------------------------------------------------------------
# Sanitization for version control
# ---------------------------------------------------------------------------


def _trim(text: Any, limit: int) -> Any:
    """Trim a free-text body to ``limit`` chars with an ellipsis; pass non-strings."""
    if isinstance(text, str) and len(text) > limit:
        return text[:limit].rstrip() + "…"
    return text


def sanitize_trace_for_commit(
    data: dict[str, Any],
    *,
    snippet_chars: int = 280,
    content_chars: int = 800,
) -> dict[str, Any]:
    """Return a copy of a loaded trace dict trimmed for version control.

    A pinned trace is committed so the chapter replays deterministically, but it
    embeds third-party web-search snippet bodies (Tavily) and the raw model
    conversation. This trims only those free-text bodies — search-result
    snippets and the ``llm_calls`` prompt/response payloads — to the length the
    notebook's display cells actually render. Everything the cells depend on is
    preserved verbatim: structured forecasts, debate arguments, supervisor
    rationale, result titles/URLs/dates, and all token counts. The defaults keep
    the rendered output identical (the timeline shows ≤``snippet_chars`` and
    ``replay_llm_calls`` shows ≤700 chars).
    """
    d = json.loads(json.dumps(data))  # deep copy, JSON-safe in/out
    for agent in d.get("agents", []):
        for trace in agent.get("traces", []):
            for result in trace.get("results", []):
                result["snippet"] = _trim(result.get("snippet"), snippet_chars)
    supervisor = d.get("supervisor")
    if supervisor:
        for results in (supervisor.get("search_results") or {}).values():
            for result in results:
                result["snippet"] = _trim(result.get("snippet"), snippet_chars)
    for call in d.get("llm_calls", []):
        for message in call.get("messages", []):
            message["content"] = _trim(message.get("content"), content_chars)
        call["response"] = _trim(call.get("response"), content_chars)
    return d


# ---------------------------------------------------------------------------
# Rehydration helpers (JSON dicts → typed schema objects)
# ---------------------------------------------------------------------------


def _rehydrate_tokens(d: dict[str, Any] | None) -> TokenUsage:
    return TokenUsage(**d) if d else TokenUsage()


def _rehydrate_search_result(d: dict[str, Any]) -> SearchResult:
    fields = {f.name for f in dataclasses.fields(SearchResult)}
    return SearchResult(**{k: v for k, v in d.items() if k in fields})


def _rehydrate_trace(d: dict[str, Any]) -> AgentTrace:
    return AgentTrace(
        step=d["step"],
        action=d["action"],
        query=d.get("query"),
        results=[_rehydrate_search_result(r) for r in d.get("results", [])],
        llm_raw=d.get("llm_raw"),
    )


def _rehydrate_agent(d: dict[str, Any]) -> AgentForecastArtifact:
    return AgentForecastArtifact(
        agent_id=d["agent_id"],
        p_yes=d["p_yes"],
        rationale=d.get("rationale", ""),
        traces=[_rehydrate_trace(t) for t in d.get("traces", [])],
        confidence=d.get("confidence", 0.5),
        sentiment=Sentiment(d.get("sentiment", "neutral")),
        key_findings=list(d.get("key_findings", [])),
        evidence_quality=EvidenceQuality(d.get("evidence_quality", "medium")),
        uncertainties=list(d.get("uncertainties", [])),
        token_usage=_rehydrate_tokens(d.get("token_usage")),
        search_queries_made=d.get("search_queries_made", 0),
        sources_consulted=d.get("sources_consulted", 0),
    )


def _rehydrate_question(d: dict[str, Any] | None) -> ForecastQuestion | None:
    if not d:
        return None
    fields = {f.name for f in dataclasses.fields(ForecastQuestion)}
    return ForecastQuestion(**{k: v for k, v in d.items() if k in fields})


def _rehydrate_debate(d: dict[str, Any] | None) -> DebateArtifact | None:
    if not d:
        return None
    return DebateArtifact(
        rounds=[DebateRound(**r) for r in d.get("rounds", [])],
        bull_final_probability=d.get("bull_final_probability"),
        bear_final_probability=d.get("bear_final_probability"),
        consensus_reached=d.get("consensus_reached", False),
        early_termination=d.get("early_termination", False),
        token_usage=_rehydrate_tokens(d.get("token_usage")),
    )


def _rehydrate_supervisor(d: dict[str, Any] | None) -> SupervisorArtifact | None:
    if not d:
        return None
    search_results = {
        q: [_rehydrate_search_result(r) for r in results]
        for q, results in (d.get("search_results") or {}).items()
    }
    return SupervisorArtifact(
        disagreements=list(d.get("disagreements", [])),
        queries=list(d.get("queries", [])),
        search_results=search_results,
        p_yes=d.get("p_yes"),
        confidence=d.get("confidence"),
        rationale=d.get("rationale"),
        resolved_disagreements=list(d.get("resolved_disagreements", [])),
        unresolved_uncertainties=list(d.get("unresolved_uncertainties", [])),
        token_usage=_rehydrate_tokens(d.get("token_usage")),
    )


# ---------------------------------------------------------------------------
# Display / replay renderers
# ---------------------------------------------------------------------------

_WIDTH = 78


def _rule(char: str = "=") -> str:
    return char * _WIDTH


def _wrap(text: str, indent: str = "    ", width: int = _WIDTH) -> str:
    text = (text or "").strip()
    if not text:
        return f"{indent}(none)"
    out: list[str] = []
    for para in text.split("\n"):
        para = para.strip()
        if not para:
            continue
        out.append(
            textwrap.fill(
                para,
                width=width,
                initial_indent=indent,
                subsequent_indent=indent,
            )
        )
    return "\n".join(out)


def show_agent_timeline(
    artifact: AgentForecastArtifact,
    *,
    snippet_chars: int = 280,
) -> str:
    """Render one agent's run as a chronological, untruncated timeline.

    Every step in order: each search query, the documents it returned (title,
    date, URL, and a snippet of the body), then the forecast with the full
    rationale, key findings, and uncertainties. This is the per-agent view
    that makes "how did this agent proceed over time" answerable at a glance.
    """
    lines = [
        _rule("="),
        f"  {artifact.agent_id.upper()}  ·  p_yes={artifact.p_yes:.2f}  "
        f"confidence={artifact.confidence:.2f}  "
        f"sentiment={artifact.sentiment.value}  "
        f"evidence={artifact.evidence_quality.value}",
        f"  searches={artifact.search_queries_made}  "
        f"sources={artifact.sources_consulted}  "
        f"tokens={artifact.token_usage.total_tokens:,}",
        _rule("="),
    ]
    for t in artifact.traces:
        if t.action == "search":
            lines.append(f'  Step {t.step} · SEARCH  "{t.query}"')
            for i, r in enumerate(t.results, 1):
                date = r.published or "?"
                lines.append(f"      {i}. [{date}] {r.title}")
                if r.url:
                    lines.append(f"         {r.url}")
                if r.snippet:
                    snip = r.snippet.strip().replace("\n", " ")
                    if len(snip) > snippet_chars:
                        snip = snip[:snippet_chars].rstrip() + "…"
                    lines.append(_wrap(snip, indent="         "))
        elif t.action == "forecast":
            lines.append(f"  Step {t.step} · FORECAST → p_yes={artifact.p_yes:.2f}")
        else:
            lines.append(f"  Step {t.step} · {t.action.upper()}")
    lines.append("")
    lines.append("  Rationale:")
    lines.append(_wrap(artifact.rationale, indent="    "))
    if artifact.key_findings:
        lines.append("  Key findings:")
        for i, f in enumerate(artifact.key_findings, 1):
            lines.append(_wrap(f"{i}. {f}", indent="    "))
    if artifact.uncertainties:
        lines.append("  Uncertainties:")
        for u in artifact.uncertainties:
            lines.append(_wrap(f"- {u}", indent="    "))
    return "\n".join(lines)


def show_agents(artifacts: list[AgentForecastArtifact], **kwargs: Any) -> str:
    """Timeline for every agent in a panel, in agent_id order."""
    ordered = sorted(artifacts, key=lambda a: a.agent_id)
    return "\n\n".join(show_agent_timeline(a, **kwargs) for a in ordered)


def show_debate_transcript(debate: DebateArtifact, *, show_evidence: bool = True) -> str:
    """Render the full bull/bear debate, round by round, with no truncation.

    Each round shows both sides' complete arguments and the key evidence they
    cited, alongside the probabilities and the gap — so the reader can see not
    just *that* the gap stayed open but *why* each side held its ground.
    """
    lines = [
        _rule("="),
        f"  DEBATE  ·  {len(debate.rounds)} round(s)  ·  "
        f"consensus={'yes' if debate.consensus_reached else 'no'}  ·  "
        f"tokens={debate.token_usage.total_tokens:,}",
        _rule("="),
    ]
    for r in debate.rounds:
        gap = abs(r.bull_probability - r.bear_probability)
        lines.append("")
        lines.append(
            f"  ── Round {r.round_number} ──  "
            f"bull={r.bull_probability:.2f}  bear={r.bear_probability:.2f}  "
            f"gap={gap:.2f}  "
            f"consensus={'yes' if r.consensus_reached else 'no'}"
        )
        lines.append(f"  BULL (p={r.bull_probability:.2f}):")
        lines.append(_wrap(r.bull_argument, indent="    "))
        if show_evidence and getattr(r, "bull_key_evidence", None):
            lines.append("    evidence:")
            for e in r.bull_key_evidence:
                lines.append(_wrap(f"- {e}", indent="      "))
        lines.append(f"  BEAR (p={r.bear_probability:.2f}):")
        lines.append(_wrap(r.bear_argument, indent="    "))
        if show_evidence and getattr(r, "bear_key_evidence", None):
            lines.append("    evidence:")
            for e in r.bear_key_evidence:
                lines.append(_wrap(f"- {e}", indent="      "))
    return "\n".join(lines)


def show_supervisor(supervisor: SupervisorArtifact) -> str:
    """Render the supervisor phase: disagreements, follow-up searches, verdict."""
    lines = [
        _rule("="),
        f"  SUPERVISOR  ·  p_yes={supervisor.p_yes}  "
        f"confidence={supervisor.confidence}  ·  "
        f"tokens={supervisor.token_usage.total_tokens:,}",
        _rule("="),
    ]
    lines.append("  Disagreements identified:")
    for d in supervisor.disagreements or ["(none)"]:
        lines.append(_wrap(f"- {d}", indent="    "))
    lines.append("  Clarifying searches:")
    for q in supervisor.queries or ["(none)"]:
        lines.append(f'    · "{q}"')
        for i, r in enumerate(supervisor.search_results.get(q, []), 1):
            lines.append(f"        {i}. [{r.published or '?'}] {r.title}")
    lines.append("  Final rationale:")
    lines.append(_wrap(supervisor.rationale or "", indent="    "))
    return "\n".join(lines)


def replay_llm_calls(
    calls: list[LLMCall],
    *,
    content_chars: int | None = None,
) -> str:
    """Replay the raw model conversation in chronological order.

    This is the lowest-level audit view: for every call, the exact prompt the
    model received (each message) and the raw text it produced. Pass
    ``content_chars`` to cap very long messages, or leave it ``None`` for the
    complete, replayable record.
    """

    def _clip(text: str) -> str:
        text = text or ""
        if content_chars is not None and len(text) > content_chars:
            return text[:content_chars].rstrip() + "…"
        return text

    lines: list[str] = []
    for c in sorted(calls, key=lambda x: x.seq):
        lines.append(_rule("="))
        tag = f" [{c.label}]" if c.label else ""
        lines.append(
            f"  CALL #{c.seq}{tag}  ·  {c.model}  ·  "
            f"json_mode={c.json_mode}  ·  "
            f"tokens in/out={c.input_tokens}/{c.output_tokens}"
        )
        lines.append(_rule("-"))
        for m in c.messages:
            lines.append(f"  ▸ {m['role'].upper()}:")
            lines.append(_wrap(_clip(m["content"]), indent="      "))
        lines.append("  ◂ RESPONSE:")
        lines.append(_wrap(_clip(c.response), indent="      "))
        lines.append("")
    return "\n".join(lines)
